-- MySQL Script generated by MySQL Workbench
-- Wed Feb 20 22:09:03 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `active` TINYINT NOT NULL,
  `surname` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `patronymic` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `get_notice` TINYINT NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_group_idx` (`group_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_group`
    FOREIGN KEY (`group_id`)
    REFERENCES `mydb`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_group` (
  `user_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  INDEX `fk_user_group_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_user_group_group1_idx` (`group_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_group_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_group_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `mydb`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`color` (
  `id` INT NOT NULL,
  `red` TINYINT UNSIGNED NOT NULL,
  `green` TINYINT UNSIGNED NOT NULL,
  `blue` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`parent_section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`parent_section` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sections` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `create_date` DATETIME NOT NULL,
  `color_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `parent_section_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sections_color1_idx` (`color_id` ASC) VISIBLE,
  INDEX `fk_sections_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_sections_parent_section1_idx` (`parent_section_id` ASC) VISIBLE,
  CONSTRAINT `fk_sections_color1`
    FOREIGN KEY (`color_id`)
    REFERENCES `mydb`.`color` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sections_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sections_parent_section1`
    FOREIGN KEY (`parent_section_id`)
    REFERENCES `mydb`.`parent_section` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` TEXT NOT NULL,
  `header` VARCHAR(255) NOT NULL,
  `creation_date` DATETIME NOT NULL,
  `recipient_user` INT NOT NULL,
  `create_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_message_user1_idx` (`create_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_message_user1`
    FOREIGN KEY (`create_user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`group`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`group` (`id`, `name`, `description`) VALUES (1, 'Ученик ', 'Группа для изучающих PHP');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`user` (`id`, `active`, `surname`, `name`, `patronymic`, `email`, `phone`, `password`, `get_notice`, `group_id`) VALUES (1, 1, 'Носков', 'Павел', 'Иванович', 'noskov_pavel@mail.ru', '89374418843', '123', 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`color`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`color` (`id`, `red`, `green`, `blue`) VALUES (1, 255, 0, 0);
INSERT INTO `mydb`.`color` (`id`, `red`, `green`, `blue`) VALUES (2, 0, 255, 0);
INSERT INTO `mydb`.`color` (`id`, `red`, `green`, `blue`) VALUES (3, 0, 0, 255);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`parent_section`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`parent_section` (`id`, `name`) VALUES (1, 'Основные');
INSERT INTO `mydb`.`parent_section` (`id`, `name`) VALUES (2, 'Оповещения');
INSERT INTO `mydb`.`parent_section` (`id`, `name`) VALUES (3, 'Спам');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`message`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`message` (`id`, `text`, `header`, `creation_date`, `recipient_user`, `create_user_id`) VALUES (1, 'Изучаю БД MYSQL', 'Изучаю', '2019-02-20 22:04:25', Учитель, 1);

COMMIT;

